### ISSUE TITLE
Some formats not compressable

### ISSUE THREAD

**Issue by jzhuoanlu** [jzhuoanlu/Image_Compression_Perrfy#6]
Here is a link to the formats pillow does support https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html. Pretty much everything is covered. I tried to add .svg images, (since I think they are pretty common) but I wasn't able to get it to work without having to add something to my path, which didn't seem too worth it.

**Comment by oruc47** [comment]
.svg not needed. Logos are already super compressed.
